#!/bin/bash -e

export PREFIX="poetry run"
export SOURCE_FILES="app"

set -x

${PREFIX} flake8 $SOURCE_FILES --ignore=E501,E722,W503,W605,F401,F403,F405
${PREFIX} black --check --diff $SOURCE_FILES
${PREFIX} mypy $SOURCE_FILES